# Site settings
title: Brad Price
email: brad.price@mail.wvu.edu
# description: 
url: "http://bradprice.io" # the base hostname & protocol for your site
# twitter_username: ajmolstad
# github_username:  ajmolstad

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Associate Professor"
excerpt_separator: "<!--more-->"
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""